### ISSUE TITLE
SpiderBuilder.CreateBuilder() 提示上下文不存在

### ISSUE THREAD

**Issue by landonzeng** [jxnkwlp/DotnetSpiderLite#2]
正好想用代理，看到了你的代码，引用后，代码里提示SpiderBuilder.CreateBuilder() 上下文不存在，这是啥情况
![微信图片_20190529174635](https://user-images.githubusercontent.com/7336781/58547509-0d0a3e80-823a-11e9-8da7-c63998ef4870.png)

**Comment by jxnkwlp** [comment]
原因是，这个 nuget 包还没有更新。   
现在已经更新了。
